// Card data for the Lake House card games.
// Cards Against Monkeys (sussy) + Cards Against the Cabin (normal): prompts (black) + responses (white).

// Blank marker used in prompt text. The UI replaces these with the chosen card(s).
export const BLANK = "_______";
export const CUSTOM_CARD_TEXT = "✍️ [Write your own answer...]";

/* ============================================================
 * CARDS AGAINST MONKEYS — the sussy / brain-rot deck.
 * ============================================================ */

// `pick` = how many response cards must be played.
// Prompts written as questions have no blank and the answer is shown beneath.
export const PROMPTS = [
  // --- Pick One ---
  { text: `Welcome to my gaming setup. Please ignore the RGB lights, the smell of energy drinks, and the massive shrine dedicated to ${BLANK}.`, pick: 1 },
  { text: `I just lost my 400-day Duolingo streak because I accidentally caught a glimpse of ${BLANK}.`, pick: 1 },
  { text: `To achieve the ultimate sigma male grindset, you must supplement your daily mewing routine with ${BLANK}.`, pick: 1 },
  { text: `What is the absolute necessary centerpiece of any respectable, multi-monitor gaming setup?`, pick: 1 },
  { text: `Bro couldn't handle the 24-hour Minecraft parkour marathon. He took one look at ${BLANK} and completely tapped out.`, pick: 1 },
  { text: `The TikTok rizz party was completely ruined when the host confidently brought out ${BLANK}.`, pick: 1 },
  { text: `My therapist said my crippling, chronic addiction to ${BLANK} is preventing me from becoming a true alpha.`, pick: 1 },
  { text: `"I literally can't watch this without Subway Surfers gameplay! Where is the ${BLANK}?!"`, pick: 1 },
  { text: `They permanently banned me from the Discord server because my primary meme format was literally just ${BLANK}.`, pick: 1 },
  { text: `Looksmaxxing is out. The new trend is improving your jawline by constantly chewing on ${BLANK}.`, pick: 1 },
  { text: `The group chat got completely silent after I dropped a 4K image of ${BLANK}.`, pick: 1 },
  { text: `What's the only thing that can distract me during a highly focused, six-hour mewing marathon?`, pick: 1 },

  // --- Pick Two ---
  { text: `You call yourself a Discord mod? You can't even talk to ${BLANK} without immediately thinking about ${BLANK}.`, pick: 2 },
  { text: `I entered the gaming room expecting ${BLANK}, but all I found was an ultrawide monitor displaying ${BLANK}.`, pick: 2 },
  { text: `The only thing standing between me and my ultimate looksmaxxing goals is ${BLANK} and a severe lack of ${BLANK}.`, pick: 2 },
  { text: `My absolute peak brain-rot setup requires three monitors: one for Subway Surfers gameplay, one for ${BLANK}, and one for ${BLANK}.`, pick: 2 },
  { text: `Instead of an intervention, my friends sat me down and tried to replace my addiction to ${BLANK} with ${BLANK}.`, pick: 2 },
  { text: `Forget astrology signs. Are you more of a ${BLANK} male, or a ${BLANK} male?`, pick: 2 },
  { text: `I'm not just a sigma, I'm an innovator. I've discovered a way to combine ${BLANK} with ${BLANK} for maximum brain-rot.`, pick: 2 },

  // --- Pick One (zesty/sussy) ---
  { text: `I knew bro was the impostor because he was acting way too zesty while ${BLANK}.`, pick: 1 },
  { text: `When the level 100 Discord mod calls you his "little sussy baka," the only appropriate response is ${BLANK}.`, pick: 1 },
  { text: `Bro couldn't survive one night in Ohio because he got caught doing the absolute zestiest ${BLANK}.`, pick: 1 },
  { text: `Emergency meeting! I just saw Red venting, and honestly, they looked incredibly zesty while holding ${BLANK}.`, pick: 1 },
  { text: `I'm not a sussy baka, I swear! I was just in electrical doing a little dance with ${BLANK}.`, pick: 1 },
  { text: `The TikTok rizz party was immediately shut down when someone hit the most zesty ${BLANK} known to mankind.`, pick: 1 },
  { text: `You can't call yourself a true gamer if your primary screen is just a 10-hour loop of ${BLANK}.`, pick: 1 },
  { text: `Drake's new album features a 12-minute interlude where he just zestily whispers about ${BLANK}.`, pick: 1 },
  { text: `They caught me being a sussy baka in 4K. My only defense in court was ${BLANK}.`, pick: 1 },
  { text: `What's the absolute zestiest thing you could possibly bring to a serious Discord meeting?`, pick: 1 },
  { text: `It's impossible to maintain your sigma grindset when the group chat keeps sending you ${BLANK}.`, pick: 1 },
  { text: `Bro thought he had that W rizz, but honestly, it just gave off massive ${BLANK} energy.`, pick: 1 },

  // --- Pick Two (zesty/sussy) ---
  { text: `First I hit 'em with the zesty ${BLANK}, then I follow it up with a sussy ${BLANK}.`, pick: 2 },
  { text: `Forget the impostor. The real threat to this spaceship is ${BLANK} combined with ${BLANK}.`, pick: 2 },
  { text: `You can't be a true sigma male if you let a sussy baka distract you with ${BLANK} and ${BLANK}.`, pick: 2 },
  { text: `My ultra-zesty morning routine involves waking up, doing a little dance, and immediately interacting with ${BLANK} and ${BLANK}.`, pick: 2 },
  { text: `I entered the chat expecting some W rizz, but instead, I was hit with a profoundly sussy ${BLANK} and an even zestier ${BLANK}.`, pick: 2 },
  { text: `Listen, if you survive the Fanum tax, the only things left to worry about are ${BLANK} and ${BLANK}.`, pick: 2 },
  { text: `The judge sentenced him to 100 hours of community service for combining a zesty ${BLANK} with a completely unhinged ${BLANK}.`, pick: 2 },
];

// Response cards — chronically-online brain-rot answers.
export const RESPONSES = [
  "✍️ [Write your own answer...]",
  "Subway Surfers gameplay",
  "an unskippable 4K Skibidi Toilet cutscene",
  "the Ohio final boss",
  "my completely untouched gym membership",
  "an aggressive Fanum tax",
  "raw, uncut sigma male grindset",
  "a GYATT of unimaginable proportions",
  "the smell of a thousand empty energy drinks",
  "uncontrollable, involuntary mewing",
  "a Labubu with dead, knowing eyes",
  "a slowly melting Grimace shake",
  "an AI girlfriend named after a Roblox character",
  "57 unwashed gaming chairs",
  "one single, perfect rizz",
  "the entire Costco free sample table",
  "my looksmaxxing surgeon's invoice",
  "a mason jar of room-temperature pre-workout",
  "the Rizzler himself",
  "Baby Gronk's NIL deal",
  "an aura reading of negative ten thousand",
  "the Hawk Tuah girl",
  "a deeply concerning Quandale Dingle situation",
  "John Pork, calling at 3 a.m.",
  "the entire unpaid Discord mod team",
  "freshly downloaded, government-grade brain rot",
  "the mitochondria, the powerhouse of the cell",
  "an RGB-lit shame closet",
  "a keyboard that crunches when you type",
  "the ick, weaponized",
  "an unspeakable quantity of Monster Energy",
  "ratio + L + you fell off",
  "touching grass for the very first time",
  "Ohio rizz",
  "the GYATT singularity",
  "a 900-day Duolingo streak held hostage",
  "my parasocial relationship with a VTuber",
  "the algorithm itself",
  "a $49.99 'escape the matrix' course",
  "my deeply unwell search history",
  "the void where my dopamine used to be",
  "a 12-hour Minecraft parkour video with no audio",
  "skibidi rizz with maximum Ohio aura",
  "a forklift certification I'll never use",
  "the W my mom said I'd never get",
  "an emotional support energy drink",
  "the last functioning brain cell in the group chat",
  "a tactical Pokémon card reseller",
  "absolutely zero bitches",
  "a suspicious amount of confidence and no plan",
  "an accidental thermal meltdown in the gooncave",
  "a Twitch streamer mid-meltdown",
  "the rizzly bear",
  "a chronically online uncle",
  "negative aura, but make it fashion",
  "an unhinged 4 a.m. grindset journal entry",
  "the forbidden second monitor",
  "a girl who's never heard the word 'Skibidi'",
  "my untreated, unsupervised dopamine deficiency",
  "a single sock and a dream",
  "the entire bottom shelf of the gas station cooler",
  "a haunted, sentient gaming setup",
  "the manosphere starter pack",
  "a motivational quote stolen from a movie villain",
  "the smell of victory and Doritos dust",
  "a fully unionized colony of feral raccoons",
  "the cringe I will never live down",
  "an inheritance spent entirely on loot boxes",
  "a podcast bro who 'just thinks logically'",
  "the audacity of a man with zero rizz",
  "an unread stack of self-help books",
  "the Wi-Fi password to enlightenment",
  "a deeply concerning, multi-monitor gooncave setup",
  "the looksmaxxing before-and-after that's just lighting",
  "an army of NPCs who all walk into the same wall",
  "a goblin in a hoodie",
  // zesty / sussy / Among Us / Drake
  "Red, venting in broad daylight",
  "a little zesty dance in electrical",
  "the emergency meeting button, slammed for no reason",
  "self-reporting my own zesty crimes in 4K",
  "faking card swipe in electrical while sweating profusely",
  "an aggressively zesty eject from the spaceship airlock",
  "a level 100 Discord mod's 'little baka' voice memo",
  "the sussiest baka in the entire lobby",
  "an unskippable 12-minute Drake interlude",
  "Drake whispering zestily about absolutely nothing",
  "a certified hood classic nobody asked for",
  "the Fanum tax collector knocking at 3 a.m.",
  "a perfectly cut scream",
  "the 'he's literally me' starter pack",
  "a 10-hour loop of the Subway Surfers victory wrap",
  "the gyatt that triggered an emergency meeting",
  "an aggressively zesty morning routine",
  "doing a little dance and immediately regretting it",
  "the impostor who was suspiciously good at electrical",
  "a sus amount of eye contact",
  "the W that was actually a profound L",
  "maximum sus, minimum rizz",
  "an unhinged amount of zest",
  "a baka so sussy it broke the lobby",
  "the vent nobody saw me climb out of",
  "a 4K replay of me being mid",
  "the group chat sending the same TikTok 40 times",
  "a wildly misplaced 'certified lover boy' caption",
  "the airlock, opening at the worst possible time",
  "a crewmate doing tasks suspiciously well",
  "the zesty whisper that ended a friendship",
  "an emotional support emergency meeting",
  "a cafeteria table covered in spilled Grimace shakes",
  "a fake task that fooled absolutely no one",
  "the silence after I said 'it's giving impostor'",
  "a Drake reaction GIF used as legal evidence",
  "the lobby's collective lack of object permanence",
  "a guy named Red who SWEARS he's innocent",
  "the most zesty thing known to mankind",
  "an unprompted sigma walk-out",
  "the ick, but make it sussy",
  "a 'trust me bro' with zero sources",
  "the brain-rot horizon, expanding daily",
  "an NPC who only says 'sus' and 'zesty'",
  "the ultimate rizz that turned into an L speedrun",
  "a deeply suspicious amount of vibe",
  "a 3 a.m. gas station existential crisis",
  "biting the dentist just to feel something",
  "accidentally texting the group chat a screenshot of the group chat",
  "lying to my therapist to avoid the psych ward",
  "crying over a room-temperature rotisserie chicken",
  "a hostage-situation corporate team-builder",
  "threatening the self-checkout with violence",
  "a bank account balance of exactly $1.43",
  "a strongly worded letter from my liver",
  "checking memes immediately after a car crash",
  "an exceptionally aggressive goose that controls my local park",
  "a multi-paragraph Reddit comment written in pure rage",
  "a text that says 'we need to talk' sent right before a 14-hour flight",
  "the quiet satisfaction of out-surviving my high school enemies",
  "talking to my parents while the edible hits",
];

/* ============================================================
 * CARDS AGAINST THE CABIN — the "normal" deck. Same game, broader
 * humor (dark, absurd, relatable) with a lake-house lean. Tamer than
 * Monkeys but still firmly an adult party game.
 * ============================================================ */

export const NORMAL_PROMPTS = [
  // --- Pick One ---
  { text: `My local HOA president showed up, took one look at ${BLANK}, and left out of respect.`, pick: 1 },
  { text: `I don't have a personality anymore. I just have ${BLANK} and a sensible pair of slacks.`, pick: 1 },
  { text: `Breaking: local man's entire bloodline ended by ${BLANK}.`, pick: 1 },
  { text: `My toxic trait is genuinely believing I can fix ${BLANK}.`, pick: 1 },
  { text: `The group chat has been eerily quiet ever since I sent ${BLANK}.`, pick: 1 },
  { text: `Therapy is expensive, so I cope with ${BLANK} instead.`, pick: 1 },
  { text: `He's not a red flag. He's an entire ${BLANK} parade.`, pick: 1 },
  { text: `My villain origin story began the day I discovered ${BLANK}.`, pick: 1 },
  { text: `The only thing keeping me tethered to reality at 4 a.m. is ${BLANK}.`, pick: 1 },
  { text: `Customs pulled me aside because of ${BLANK}.`, pick: 1 },
  { text: `What does my FBI agent refuse to make eye contact with me about?`, pick: 1 },
  { text: `I told the doctor "it hurts when I do this," and "this" was ${BLANK}.`, pick: 1 },
  { text: `Rome fell eventually. Honestly, ${BLANK} would've finished the job faster.`, pick: 1 },
  { text: `My entire screen-time report is just ${BLANK}.`, pick: 1 },
  { text: `Welcome to my TED Talk. Today's topic: why ${BLANK} is the root of all my problems.`, pick: 1 },
  { text: `The lake-house weekend descended into chaos the second someone mentioned ${BLANK}.`, pick: 1 },
  { text: `I'd trade my entire 401(k) for one more hit of ${BLANK}.`, pick: 1 },
  { text: `What instantly turns any gas-station bathroom into an active crime scene?`, pick: 1 },
  { text: `According to my Spotify Wrapped, my whole year was just ${BLANK}.`, pick: 1 },
  { text: `I'm built different. Specifically, I'm built out of ${BLANK} and pure spite.`, pick: 1 },
  { text: `He pulled up to the function with ${BLANK} and genuinely thought it was a flex.`, pick: 1 },
  { text: `The horror movie would've ended in five minutes if they'd just had ${BLANK}.`, pick: 1 },
  { text: `My grandma found my phone, and now she only knows me as the guy who's into ${BLANK}.`, pick: 1 },
  { text: `Nothing humbles a grown man faster than ${BLANK}.`, pick: 1 },
  { text: `I will not be taking any further questions about ${BLANK}.`, pick: 1 },
  { text: `The aux got revoked the instant I played ${BLANK}.`, pick: 1 },
  { text: `What is currently rotting at the very bottom of my backpack?`, pick: 1 },
  { text: `Every night I lie awake, haunted by the memory of ${BLANK}.`, pick: 1 },
  { text: `My personal brand is 90% vibes and 10% ${BLANK}.`, pick: 1 },
  { text: `The Wi-Fi died at the cabin, and within an hour we'd resorted to ${BLANK}.`, pick: 1 },
  { text: `They say money can't buy happiness, but it can buy ${BLANK}, which is close enough.`, pick: 1 },
  { text: `I lost the family fishing trophy this year because of ${BLANK}.`, pick: 1 },
  { text: `My last two brain cells are currently fighting to the death over ${BLANK}.`, pick: 1 },
  { text: `What would get me immediately removed from a child's birthday party?`, pick: 1 },
  { text: `The secret ingredient in grandma's award-winning casserole was always ${BLANK}.`, pick: 1 },
  { text: `I peaked in high school, and the only proof left is ${BLANK}.`, pick: 1 },
  { text: `Officer, I can absolutely explain ${BLANK}.`, pick: 1 },
  { text: `My whole bloodline's curse can be traced directly back to ${BLANK}.`, pick: 1 },
  { text: `Nobody warned me that adulthood was mostly just ${BLANK}.`, pick: 1 },
  { text: `The campfire went silent the moment Dad confessed to ${BLANK}.`, pick: 1 },

  // --- Pick Two ---
  { text: `My therapist diagnosed me with ${BLANK} and a crippling dependence on ${BLANK}.`, pick: 2 },
  { text: `The recipe for the perfect lake-house weekend: equal parts ${BLANK} and ${BLANK}.`, pick: 2 },
  { text: `I told her I'm a simple man with simple needs: ${BLANK} and ${BLANK}.`, pick: 2 },
  { text: `Forget fight-or-flight. My nervous system only knows ${BLANK} and ${BLANK}.`, pick: 2 },
  { text: `The situationship started with ${BLANK} and ended, predictably, with ${BLANK}.`, pick: 2 },
  { text: `My two personalities: ${BLANK} in public, and ${BLANK} at 3 a.m.`, pick: 2 },
  { text: `Heaven is ${BLANK}. Hell is ${BLANK}. I have visited both this week.`, pick: 2 },
  { text: `The ick went from 0 to 100 the moment he combined ${BLANK} with ${BLANK}.`, pick: 2 },
  { text: `My entire financial plan is ${BLANK} now and ${BLANK} later.`, pick: 2 },
  { text: `The cult had two rules: never discuss ${BLANK}, and always protect ${BLANK}.`, pick: 2 },
  { text: `I childproofed the whole cabin but completely forgot about ${BLANK} and ${BLANK}.`, pick: 2 },
  { text: `My dating profile just reads: "into ${BLANK}, violently allergic to ${BLANK}."`, pick: 2 },
  { text: `The group project collapsed because Kevin brought ${BLANK} instead of ${BLANK}.`, pick: 2 },
  { text: `Evolution blessed me with ${BLANK} but cruelly denied me ${BLANK}.`, pick: 2 },
  { text: `The neighborhood council meeting approved ${BLANK}, which immediately demanded ${BLANK}.`, pick: 2 },
  { text: `My will leaves ${BLANK} to my enemies and ${BLANK} to my cat.`, pick: 2 },
  { text: `The wedding was perfect until the best man's speech brought up ${BLANK} and ${BLANK}.`, pick: 2 },
  { text: `Customs waved me through with ${BLANK} but somehow seized my ${BLANK}.`, pick: 2 },
  { text: `My morning routine: ${BLANK} before coffee, ${BLANK} before regret.`, pick: 2 },
  { text: `He proposed with ${BLANK} instead of a ring, then followed it up with ${BLANK}.`, pick: 2 },
  { text: `The apocalypse starter pack: ${BLANK}, ${BLANK}, and zero survival skills.`, pick: 2 },
  { text: `The lake monster surfaced, took ${BLANK}, and left behind only ${BLANK}.`, pick: 2 },
  { text: `Two things school never taught me: how to do taxes, and how to survive ${BLANK} and ${BLANK}.`, pick: 2 },
  { text: `I manifested ${BLANK}, and the universe sarcastically handed me ${BLANK}.`, pick: 2 },
  { text: `The campfire confessions spiraled when Aunt Linda admitted to ${BLANK} and ${BLANK}.`, pick: 2 },
  { text: `My entire twenties were just ${BLANK} fueled by ${BLANK}.`, pick: 2 },
  { text: `My performance review flagged two "areas for improvement": ${BLANK} and ${BLANK}.`, pick: 2 },
  { text: `The genie granted exactly two wishes: ${BLANK}, and the eternal curse of ${BLANK}.`, pick: 2 },
  { text: `Pro tip: never mix ${BLANK} with ${BLANK} unless you want to end up on a watchlist.`, pick: 2 },
  { text: `The family reunion split into two camps: team ${BLANK} and team ${BLANK}.`, pick: 2 },
  { text: `My comfort show is just ${BLANK}, and my comfort food is, regrettably, ${BLANK}.`, pick: 2 },
  { text: `He texted "we need to talk" and showed up holding ${BLANK} and ${BLANK}.`, pick: 2 },
  { text: `My entire sleep schedule is held together by ${BLANK} and ${BLANK}.`, pick: 2 },
  { text: `The boat sank because someone absolutely insisted on bringing ${BLANK} AND ${BLANK}.`, pick: 2 },
  { text: `My personality test came back with two results: ${BLANK} and a deeply concerning amount of ${BLANK}.`, pick: 2 },
  { text: `They erected a statue of me holding ${BLANK} in one hand and ${BLANK} in the other.`, pick: 2 },
  { text: `Step one: ${BLANK}. Step two: ??? Step three: ${BLANK}.`, pick: 2 },
  { text: `The escape room left us two clues: ${BLANK} and ${BLANK}. We are, to this day, still in there.`, pick: 2 },
  { text: `My red flag is ${BLANK}. My green flag is, somehow, also ${BLANK}.`, pick: 2 },
  { text: `The reunion photo was ruined by ${BLANK} and, in the background, ${BLANK}.`, pick: 2 },
];

export const NORMAL_RESPONSES = [
  "✍️ [Write your own answer...]",
  // lake-house / cabin flavored
  "a canoe full of regret",
  "the dock where I lost my last shred of dignity",
  "skinny dipping at the worst possible time",
  "a deeply cursed s'more",
  "the lake monster everyone pretends isn't real",
  "a jet ski I cannot afford and cannot drive",
  "the in-laws arriving two days early",
  "a screaming loon at 4 a.m.",
  "an inflatable flamingo with too much attitude",
  "the group chat planning a trip that will never happen",
  "wet socks for the entire weekend",
  "a tackle box full of bad decisions",
  "the one mosquito that ruins everything",
  "grandma's terrifyingly competitive card-game face",
  "a cooler containing only mustard",
  "the bonfire that got slightly out of hand",
  "a paddleboard yoga influencer",
  "the cabin's haunted board game",
  "a fish that maintained eye contact",
  "the 'fun' family hike from hell",
  "an overconfident kayak flip",
  "a sunburn shaped like regret",
  "the neighbor's suspiciously loud generator",
  "a raccoon that learned to open the cooler",
  "the lake water you definitely shouldn't swallow",
  "an unhinged amount of bug spray",
  "a dad violently arguing with Google Maps in a dead zone",
  "a banana boat ride gone deeply wrong",
  "the campfire story that traumatized the kids",
  "a dock plank that gives everyone splinters",
  "the smug confidence of a man with no sunscreen",
  "a goose with a personal vendetta",
  "the 'quick' five-hour fishing trip",
  "an entire weekend of competitive pontoon energy",
  "the floatie that drifted into the next county",
  "a suspiciously damp deck of cards",
  "the s'mores-to-mosquito-bite ratio",
  "an aggressively patriotic speedboat",
  "the cabin's single, judgmental cat",
  "a thermos of unidentifiable lake-house punch",
  "flipping the Monopoly board directly into the campfire",
  "a beanbag-toss rivalry that ended a friendship",
  "the dock cannonball that emptied the lake",
  "a tan line shaped like a phone",
  "an emotionally complex pontoon boat",
  "the kayak that betrayed me",
  // general / dark / absurd
  "an aggressively confident wrong answer",
  "raw, unfiltered second-hand embarrassment",
  "a single, devastating left swipe",
  "the entire concept of object permanence",
  "a USB stick full of crimes",
  "my dad's 'I'm not mad, just disappointed' voice",
  "an unpaid internship that somehow charges rent",
  "a gas-station hot dog of deeply unknown origin",
  "the confidence of a man who has never once been told no",
  "a group project where I did literally everything",
  "spontaneous crying in a Target parking lot",
  "the last slice of pizza, weaponized",
  "a haunted Roomba seeking vengeance",
  "an HR violation waiting to happen",
  "one (1) functioning brain cell, currently on strike",
  "a deeply unserious amount of credit card debt",
  "a PowerPoint titled 'Why You Should Date Me'",
  "a raccoon wearing my exact outfit",
  "the precise moment it all went wrong",
  "an essential oil that cures absolutely nothing",
  "a confidently incorrect Wikipedia edit",
  "the smell of a freshly cracked can of regret",
  "crippling debt disguised as self-care",
  "a motivational speaker with zero accomplishments",
  "an air fryer I use exclusively to cry near",
  "a fully sentient pile of unfolded laundry",
  "the audacity, the gall, the absolute nerve",
  "a screenshot that ended a 12-year friendship",
  "my entire dignity, sold for clout",
  "a parking spot defended to the death",
  "an inflatable swan with a clear attitude problem",
  "a cease-and-desist letter from my own mother",
  "waking up from a 9-hour 'nap' with zero concept of time",
  "a profound, existential dread cured only by toasted s'mores",
  "a casserole nobody asked for and everyone fears",
  "a stack of unopened Amazon boxes holding my dopamine hostage",
  "an unhinged voicemail left at 2 a.m.",
  "a fish that has clearly seen some things",
  "re-staining the deck with my tears",
  "fake-coughing to cover a campfire sob",
  "a serial killer's unhinged LinkedIn post",
  "accidentally feuding with a 12-year-old on Roblox",
  "thinking I could land a commercial airliner in an emergency",
  "a microwave that only heats the bowl",
  "faking my death to avoid the family reunion",
  "a strongly worded email from the local homeowners association",
  "throwing the Monopoly board into the bonfire",
  "explaining late-stage capitalism to a toddler",
  "an inflatable flamingo that is slowly and ominously deflating",
  "pretending to know how to start the boat while sweating through my shirt",
  "a cooler that was left unplugged in the summer heat for three days",
  "planning my escape during direct eye contact",
  "the precise moment I realized there is no Wi-Fi at this cabin",
  "arguing with a Canadian goose over who owns the dock",
  "being held together by caffeine, spite, and phone chargers",
];

/* ============================================================
 * Bonus games
 * ============================================================ */

// Bonus deck: "Lake House Truths" — cozy + chaotic prompts to read aloud and answer.
export const LAKE_TRUTHS = [
  { type: "Would You Rather", text: "Would you rather spend the whole weekend with no Wi-Fi, or no hot water?" },
  { type: "Would You Rather", text: "Would you rather fall off the dock fully clothed, or get caught singing to yourself in the kayak?" },
  { type: "Would You Rather", text: "Would you rather share a bunk bed with a snorer, or a sleep-talker who narrates dreams?" },
  { type: "Would You Rather", text: "Would you rather always be the one who packs the snacks, or always be the one who drives?" },
  { type: "Would You Rather", text: "Would you rather swim across the whole lake, or run the entire shoreline trail?" },
  { type: "Would You Rather", text: "Would you rather win every card game but lose every fishing contest, or vice versa?" },
  { type: "Never Have I Ever", text: "Never have I ever capsized a canoe on purpose." },
  { type: "Never Have I Ever", text: "Never have I ever pretended to know how to start the boat." },
  { type: "Never Have I Ever", text: "Never have I ever eaten a s'more that was 90% marshmallow goo." },
  { type: "Never Have I Ever", text: "Never have I ever 'accidentally' splashed someone who deserved it." },
  { type: "Never Have I Ever", text: "Never have I ever lost a flip-flop to the lake forever." },
  { type: "Truth", text: "What's the most chaotic thing that's ever happened on a family trip?" },
  { type: "Truth", text: "Who in this group would survive longest stranded on the lake's tiny island?" },
  { type: "Truth", text: "What's your most embarrassing 'outdoorsy' fail?" },
  { type: "Truth", text: "If the cabin were haunted, whose fault would it be?" },
  { type: "Dare", text: "Do your best loon call. Loudly. Right now." },
  { type: "Dare", text: "Narrate the next 60 seconds like a nature documentary." },
  { type: "Dare", text: "Give a dramatic toast to the lake as if you'll never see it again." },
  { type: "Dare", text: "Convince everyone you caught a fish 'this big' with a straight face." },
  { type: "Most Likely To", text: "Who's most likely to fall asleep in the hammock and miss dinner?" },
  { type: "Most Likely To", text: "Who's most likely to start a competitive feud over a board game?" },
  { type: "Most Likely To", text: "Who's most likely to befriend the lake's resident goose?" },
  { type: "Most Likely To", text: "Who's most likely to 'just check work email' on vacation?" },
];

// Would You Rather: Unhinged — chronically-online dilemmas. Read both, everyone votes.
export const WOULD_YOU_RATHER = [
  { tag: "Would You Rather", text: "Lose your entire 400-day streak, or have the group chat read your search history out loud?" },
  { tag: "Would You Rather", text: "Get caught venting in 4K, or get Fanum-taxed every single meal for a year?" },
  { tag: "Would You Rather", text: "Only communicate in TikTok audios forever, or only in Drake lyrics forever?" },
  { tag: "Would You Rather", text: "Be the sussiest baka in every lobby, or the zestiest dancer in every electrical?" },
  { tag: "Would You Rather", text: "Have permanent W rizz but a -1000 aura, or perfect aura but the rizz of a damp sock?" },
  { tag: "Would You Rather", text: "Survive one night in Ohio, or one emergency meeting where everyone votes you out?" },
  { tag: "Would You Rather", text: "Have your jawline maxed but mew incorrectly forever, or perfect mewing and a chin like a melted candle?" },
  { tag: "Would You Rather", text: "Be looped into a 10-hour Subway Surfers stream, or a 12-minute Drake whisper interlude on repeat?" },
  { tag: "Would You Rather", text: "Be known forever as 'the impostor', or forever as 'the little sussy baka'?" },
  { tag: "Would You Rather", text: "Never touch grass again, or never touch your phone again?" },
  { tag: "Would You Rather", text: "Get rizzed up by an NPC, or ratio'd by your own grandma in the group chat?" },
  { tag: "Would You Rather", text: "Have a gyatt that triggers emergency meetings, or rizz that triggers second-hand embarrassment?" },
  { tag: "Would You Rather", text: "Win every argument but only in Ohio, or be right everywhere but nobody believes you?" },
  { tag: "Would You Rather", text: "Be sentenced to 100 hours of cringe community service, or 100 hours of forced grindset content?" },
  { tag: "Would You Rather", text: "Have everything you say auto-tuned by Drake, or auto-captioned as 'sus'?" },
  { tag: "Would You Rather", text: "Be the level 100 Discord mod nobody respects, or the new guy everyone calls 'baka'?" },
  { tag: "Would You Rather", text: "Get the W but it's the zestiest W imaginable, or take the L with maximum aura intact?" },
  { tag: "Would You Rather", text: "Only RGB-led lighting for the rest of your life, or only fluorescent gas-station lighting?" },
];

// Red Flag / Green Flag — read a trait aloud, group debates and shouts the verdict.
export const RED_GREEN = [
  { tag: "Red or Green?", text: "Their entire personality is one TikTok audio." },
  { tag: "Red or Green?", text: "Refers to their bedroom, unironically, as 'the command center'." },
  { tag: "Red or Green?", text: "Calls everyone 'little sussy baka', including their boss." },
  { tag: "Red or Green?", text: "Has a 400-day streak of something they refuse to explain." },
  { tag: "Red or Green?", text: "Hits the emergency meeting button over the smallest inconvenience." },
  { tag: "Red or Green?", text: "Mews in the middle of the conversation and expects you not to notice." },
  { tag: "Red or Green?", text: "Sends 40 identical TikToks and then says 'you up?'" },
  { tag: "Red or Green?", text: "Their love language is Fanum-taxing your fries." },
  { tag: "Red or Green?", text: "Claims a -1000 aura reading like it's a flex." },
  { tag: "Red or Green?", text: "Does a little zesty dance before every important decision." },
  { tag: "Red or Green?", text: "Will not stop quoting Drake during a breakup." },
  { tag: "Red or Green?", text: "Maxed their jawline but lost the ability to make eye contact." },
  { tag: "Red or Green?", text: "Self-reports their own tasks and acts shocked when ejected." },
  { tag: "Red or Green?", text: "Owns a single sock and calls it 'the setup'." },
  { tag: "Red or Green?", text: "Brings up their sigma grindset at a funeral." },
  { tag: "Red or Green?", text: "Has an AI girlfriend AND is jealous of her." },
  { tag: "Red or Green?", text: "Touches grass exactly once and posts a 9-slide carousel about it." },
  { tag: "Red or Green?", text: "Negotiates the Fanum tax with a signed contract." },
  { tag: "Red or Green?", text: "Whispers 'it's giving impostor' at every party." },
  { tag: "Red or Green?", text: "Three monitors, one is exclusively for Subway Surfers." },
  { tag: "Red or Green?", text: "Says 'trust me bro' and is somehow always wrong." },
  { tag: "Red or Green?", text: "Replaces 'I love you' with 'you got that W rizz'." },
];

// Most Likely To — used by Emergency Meeting (voting game).
export const MOST_LIKELY = [
  "get voted off the spaceship first, fairly",
  "be the actual impostor and get away with it",
  "lose a 400-day streak to a single notification",
  "start an emergency meeting over literally nothing",
  "have the most cursed search history in the room",
  "call their crush 'little sussy baka' out loud",
  "fake all their tasks and self-report with confidence",
  "do a zesty little dance at the worst possible moment",
  "get Fanum-taxed and say thank you",
  "claim a -1000 aura reading as a personality trait",
  "fall for an obvious 'trust me bro'",
  "quote Drake during an actual emergency",
  "mew through an entire serious conversation",
  "survive the longest stranded in Ohio",
  "turn a guaranteed W into a speedrun L",
  "get caught being sus in 4K",
  "have three monitors and accomplish nothing",
  "become a level 100 Discord mod and abuse it",
  "vent in front of everyone and act innocent",
  "send the same TikTok to the group chat 40 times",
  "touch grass and immediately post about it",
  "rizz up an NPC and get rejected",
  "defend their search history in a court of law",
  "be the reason the group chat got muted",
];

// Rizz Roulette — the unhinged, brain-rot party mode. Draw a card and do the thing:
// deliver the rizz, spill the confession, commit to the dare, or defend the hot take.
export const RIZZ_ROULETTE = [
  { tag: "Rizz Challenge", text: "To the person on your left, full eye contact, no laughing: \"Are you a 400-day streak? Because losing you would absolutely destroy me.\"" },
  { tag: "Rizz Challenge", text: "Deliver with total confidence: \"You must be from Ohio, because you've got me acting unbelievably sus.\"" },
  { tag: "Rizz Challenge", text: "Straight face: \"Is your name Wi-Fi? Because I'm sensing a deep, unspoken connection.\"" },
  { tag: "Rizz Challenge", text: "Say it like you mean it: \"You've got that W rizz… can I please get your aura reading?\"" },
  { tag: "Rizz Challenge", text: "No breaking: \"Call me a Labubu, because I'd let you put me on a shelf and just stare.\"" },
  { tag: "Rizz Challenge", text: "To the room: \"Are we in electrical? Because you're making me want to do a little dance.\"" },
  { tag: "Rizz Challenge", text: "Commit fully: \"You're so gyatt-tier my mewing technique improved just looking at you.\"" },
  { tag: "Rizz Challenge", text: "Whisper it like Drake: \"Are you a Fanum tax? Because you're about to take everything I've got.\"" },
  { tag: "Confession", text: "Reveal your most-used emoji and let the group psychoanalyze your entire soul." },
  { tag: "Confession", text: "Show the last photo in your camera roll. No scrolling, no excuses." },
  { tag: "Confession", text: "What app is doing the most damage to your screen-time report? Say the number." },
  { tag: "Confession", text: "Admit the single cringiest thing you've ever texted someone you liked." },
  { tag: "Confession", text: "Name a 'W' you once bragged about that was, in hindsight, a profound L." },
  { tag: "Confession", text: "Confess your most embarrassing parasocial relationship. We won't judge (we will)." },
  { tag: "Confession", text: "What's your 3 a.m. villain-origin-story snack? Be honest." },
  { tag: "Confession", text: "Reveal the most unhinged search you've made in the last month." },
  { tag: "Dare", text: "Deliver a 20-second motivational sigma-grindset speech. Mean every word." },
  { tag: "Dare", text: "Do your zestiest victory dance, like you just cleared every task in electrical." },
  { tag: "Dare", text: "Read your last sent text out loud, but in a full Drake whisper voice." },
  { tag: "Dare", text: "Rizz up an inanimate object in the room. Commit until someone is uncomfortable." },
  { tag: "Dare", text: "Hold dead-eyed eye contact with the person across from you for 15 seconds. No smiling." },
  { tag: "Dare", text: "Narrate the next 30 seconds of this room like an Among Us emergency meeting." },
  { tag: "Dare", text: "Perform your most convincing 'gyatt' reaction to absolutely nothing." },
  { tag: "Dare", text: "Speak only in NPC voice lines until your next turn." },
  { tag: "Hot Take", text: "Defend for 30 seconds, no breaking: \"Cereal is a soup, and disagreeing reveals negative aura.\"" },
  { tag: "Hot Take", text: "Defend it: \"Texting back instantly is a green flag; making someone wait is a war crime.\"" },
  { tag: "Hot Take", text: "Defend it: \"Being 'mysterious' is just having no personality but good lighting.\"" },
  { tag: "Hot Take", text: "Defend it: \"Everyone has had an Ohio phase. Describe yours in detail.\"" },
  { tag: "Hot Take", text: "Defend it: \"Showering at night is morally superior to showering in the morning.\"" },
  { tag: "Hot Take", text: "Defend it: \"The group chat would not survive a single day without you, specifically.\"" },
  { tag: "Hot Take", text: "Defend it: \"Pineapple on pizza is elite and this is genuinely non-negotiable.\"" },
  { tag: "Hot Take", text: "Defend it: \"Touching grass is overrated; the indoors has never betrayed me.\"" },
];

/* ============================================================
 * CARDS AGAINST THE FAMILY — edgy, silly, family-friction PG-13.
 * ============================================================ */
export const FAMILY_PROMPTS = [
  // --- Silly / Cozy ---
  { text: "Mom's secret ingredient in her award-winning campfire chili is actually _.", pick: 1 },
  { text: "Dad spent six hours in the hardware store looking for the perfect _.", pick: 1 },
  { text: "What is secretly hiding under the back seat of the family minivan?", pick: 1 },
  { text: "Our dog ran away into the woods because he caught a glimpse of _.", pick: 1 },
  { text: "The local park ranger warned us to lock up our coolers because the bears have developed a taste for _.", pick: 1 },
  { text: "My teacher didn't believe me when I told her my homework was destroyed by _.", pick: 1 },
  { text: "Instead of chores this weekend, dad surprised us by organizing a family contest of _.", pick: 1 },
  { text: "What's the absolute worst thing you could accidentally drop into the campfire?", pick: 1 },
  { text: "Grandma's favorite cabin activity is sitting on the porch and complaining about _.", pick: 1 },
  { text: "We knew the lake water was freezing when dad jumped in and screamed about _.", pick: 1 },
  { text: "First comes the smell of _, then comes the sound of _.", pick: 2 },
  { text: "I tried to build a custom treehouse using nothing but _ and _.", pick: 2 },
  { text: "Instead of clean laundry, my suitcase was completely filled with _ and _.", pick: 2 },
  { text: "The ultimate campfire s'more contains two graham crackers, a toasted marshmallow, and a slice of _.", pick: 1 },
  { text: "What did the fisherman accidentally reel in instead of a trout?", pick: 1 },
  { text: "My sibling got grounded for a week because they tried to feed the raccoons _.", pick: 1 },
  { text: "What is the secret cabin rule that nobody actually follows?", pick: 1 },

  // --- Edgy PG-13 Family Friction / Roasts ---
  { text: "My sibling was grounded for two weeks after mom found _ hidden under their bed.", pick: 1 },
  { text: "I knew my brother was lying about cleaning his room because I found _ in his closet.", pick: 1 },
  { text: "Nothing ruins a peaceful family road trip faster than dad threatening to turn the car around because of _.", pick: 1 },
  { text: "What is the real reason why my sister has been locked in the bathroom for three hours?", pick: 1 },
  { text: "Chore evasion is an art. My sibling's ultimate masterpiece was avoiding unloading the dishwasher by pretending to suffer from _.", pick: 1 },
  { text: "Why does the family dog secretly love my sibling more than me?", pick: 1 },
  { text: "Mom's strict kitchen rules are getting out of hand. Yesterday she literally banned _.", pick: 1 },
  { text: "What is secretly inside mom's locked 'secret stash' drawer in the kitchen?", pick: 1 },
  { text: "Dad's famous 'special recipe' barbecue is just normal burgers covered in _.", pick: 1 },
  { text: "I managed to escape setting the dinner table by creating a massive distraction involving _.", pick: 1 },
  { text: "The family group chat got completely silent after dad confidently messaged a photo of _.", pick: 1 },
  { text: "My sibling's search history is completely filled with _ and _.", pick: 2 },
  { text: "To survive a 10-hour family road trip, you need a high-tolerance for _ and a massive supply of _.", pick: 2 }
];

export const FAMILY_RESPONSES = [
  "✍️ [Write your own answer...]",
  "a canoe full of melted marshmallows",
  "dad's terrible, off-beat dance moves",
  "a squirrel wearing tiny sunglasses",
  "wet socks that have been sitting in a bag for three days",
  "an absolute overload of maple syrup",
  "a family board game that ends in an argument",
  "a raccoon wearing a detective hat",
  "accidentally eating a bug while riding a bicycle",
  "dad's cheesy, laugh-at-his-own-jokes humor",
  "an extremely muddy pair of boots",
  "trying to catch a frog with bare hands",
  "a massive pile of sticky pinecones",
  "the absolute loudest snore in the cabin",
  "stealing the last marshmallow from the bag",
  "a fish that looks like it's judging my life choices",
  "accidentally dropping my phone in the lake",
  "a mountain of unwashed beach towels",
  "sleeping in a tent that has a tiny leak",
  "an army of very polite ants",
  "a soggy peanut butter and jelly sandwich",
  "trying to skip a flat stone but splashing myself",
  "a cooler full of nothing but broccoli",
  "mom's famous burnt hot dogs",
  "a mosquito that just won't leave me alone",
  "singing campfire songs completely out of tune",
  "a very confused duck in a life jacket",
  "wearing my shirt inside out all day without realizing",
  "a massive splash from a clumsy cannonball jump",
  "grandma's secret stash of chocolate chip cookies",
  "a tree branch that looks exactly like a dinosaur",
  "getting a marshmallow stuck to my forehead",
  "an entire day spent entirely in wet swimsuits",
  "a very ambitious beaver with a tiny hardhat",

  // --- Edgy PG-13 Family Additions ---
  "mom's highly classified snack stash",
  "a deeply concerning, unwashed heap of gym clothes",
  "my sibling's questionable browser history",
  "accidentally calling the teacher 'Mom'",
  "chore evasion tactics that actually worked",
  "pretending to be asleep to avoid unloading the dishwasher",
  "an incredibly dramatic teenage tantrum",
  "wearing the same socks for four days straight",
  "blaming the dog for a mysterious smell in the living room",
  "my sister's 10-hour beauty routine",
  "dad trying to use modern slang and failing miserably",
  "the terrifying moment mom calls you by your full middle name",
  "stealing my sibling's phone charger out of their wall",
  "doing the absolute bare minimum to clean my room",
  "blaming my sibling for the dent in the minivan",
  "dad's absolute worst cooking disaster",
  "an hour-long lecture about leaving the lights on",
  "getting caught eating shredded cheese directly from the bag at 2 a.m.",
  "trying to explain why my chore checklist isn't actually completed",
  "pretending to lose the TV remote to hide it from my sibling"
];

/* ============================================================
 * SIBLING RIVALRY — PG-13 edgy dares, roasts, and dilemmas.
 * ============================================================ */
export const SIBLING_RIVALRY = [
  { tag: "Roast", text: "Point at the sibling most likely to lose their phone while it is literally in their hand." },
  { tag: "Rare Dare", text: "Do an imitation of how your sibling reacts when they are told to unload the dishwasher." },
  { tag: "Dilemma", text: "Would you rather have to wear your sibling's unwashed gym socks for a week, OR wash dad's muddy boots with your toothbrush?" },
  { tag: "Confession", text: "Confess the cringiest, most elaborate lie you've ever told to get your sibling in trouble." },
  { tag: "Roast", text: "Who has the absolute worst screen-time report at this table? Call them out." },
  { tag: "Roast", text: "Who in this cabin is secretly the most dramatic over minor inconveniences? Give an example." },
  { tag: "Rare Dare", text: "Show the room your sibling's cringiest contact photo or name in your phone." },
  { tag: "Dilemma", text: "Would you rather have your sibling control your Spotify playlist for a whole month, OR have them write all your texts for a day?" },
  { tag: "Confession", text: "What is the biggest thing you broke or lost that belonged to your sibling that they still think was an accident?" },
  { tag: "Challenge", text: "Give your sibling a 10-second sincere compliment, but you must keep a completely straight, dead-eyed face. No smiling!" },
  { tag: "Roast", text: "If your sibling was an Among Us crewmate, what task would they be caught failing zesty-style in electrical?" }
];

/* ============================================================
 * FAMILY ROASTS — PG-13 campfire truths, dares, and roasts.
 * ============================================================ */
export const FAMILY_ROASTS = [
  { tag: "Roast", text: "Describe dad's absolute worst fashion choice or outfit in full, painful detail." },
  { tag: "Roast", text: "Who in the family takes the longest to get ready for a simple trip to the supermarket?" },
  { tag: "Truth", text: "What is the most embarrassing thing your parents have ever done in front of your friends?" },
  { tag: "Challenge", text: "Give a 30-second passionate speech defending why your parents' curfew/rules are 'literally unfair.'" },
  { tag: "Roast", text: "Who is the pickiest eater at this table? What is their most dramatic food complaint?" },
  { tag: "Truth", text: "What is the cringiest dad joke dad has ever confidently told in public?" },
  { tag: "Roast", text: "Who in the family is most likely to get completely lost in a tiny supermarket aisle?" },
  { tag: "Challenge", text: "Do your best imitation of mom realizing that somebody forgot to take the chicken out of the freezer." },
  { tag: "Truth", text: "What family vacation was the biggest disaster, and who was primarily responsible for it?" },
  { tag: "Roast", text: "Who at this table is the worst backseat driver? Imitate their standard complaints." }
];
