// Card data for the Lake House card games.
// Cards Against Monkeys: an adult party game. Prompts (black) + responses (white).

// Blank marker used in prompt text. The UI replaces these with the chosen card(s).
export const BLANK = "_______";

// Prompt cards. `pick` = how many response cards must be played.
// Prompts written as questions have no blank and the answer is shown beneath.
export const PROMPTS = [
  // --- Pick One ---
  { text: `Welcome to my gooncave. Please ignore the LED lights, the smell, and the massive shrine dedicated to ${BLANK}.`, pick: 1 },
  { text: `I just lost my 400-day edging streak because I accidentally caught a glimpse of ${BLANK}.`, pick: 1 },
  { text: `To achieve the ultimate sigma male grindset, you must supplement your daily mewing routine with ${BLANK}.`, pick: 1 },
  { text: `What is the absolute necessary centerpiece of any respectable, multi-monitor gooncave?`, pick: 1 },
  { text: `Bro couldn't handle the marathon gooning session. He took one look at ${BLANK} and completely tapped out.`, pick: 1 },
  { text: `The TikTok rizz party was completely ruined when the host confidently brought out ${BLANK}.`, pick: 1 },
  { text: `My therapist said my crippling, chronic addiction to ${BLANK} is preventing me from becoming a true alpha.`, pick: 1 },
  { text: `"I literally can't goon to this! Where is the ${BLANK}?!"`, pick: 1 },
  { text: `They permanently banned me from the Discord server because my primary gooning material was literally just ${BLANK}.`, pick: 1 },
  { text: `Looksmaxxing is out. The new trend is improving your jawline by constantly chewing on ${BLANK}.`, pick: 1 },
  { text: `The group chat got completely silent after I dropped a 4K image of ${BLANK}.`, pick: 1 },
  { text: `What's the only thing that can distract me during a highly focused, six-hour edging marathon?`, pick: 1 },

  // --- Pick Two ---
  { text: `You call yourself a goon commander? You can't even edge to ${BLANK} without immediately thinking about ${BLANK}.`, pick: 2 },
  { text: `I entered the gooncave expecting ${BLANK}, but all I found was an ultrawide monitor displaying ${BLANK}.`, pick: 2 },
  { text: `The only thing standing between me and my ultimate looksmaxxing goals is ${BLANK} and a severe lack of ${BLANK}.`, pick: 2 },
  { text: `My absolute peak brain-rot setup requires three monitors: one for Subway Surfers gameplay, one for ${BLANK}, and one for ${BLANK}.`, pick: 2 },
  { text: `Instead of an intervention, my friends sat me down and tried to replace my addiction to ${BLANK} with ${BLANK}.`, pick: 2 },
  { text: `Forget astrology signs. Are you more of a ${BLANK} male, or a ${BLANK} male?`, pick: 2 },
  { text: `I'm not just a gooner, I'm an innovator. I've discovered a way to combine ${BLANK} with ${BLANK} for maximum brain-rot.`, pick: 2 },
];

// Response cards — chronically-online brain-rot answers.
export const RESPONSES = [
  "Subway Surfers gameplay",
  "an unskippable 4K Skibidi Toilet cutscene",
  "the Ohio final boss",
  "my completely untouched gym membership",
  "an aggressive Fanum tax",
  "raw, uncut sigma male grindset",
  "a GYATT of unimaginable proportions",
  "the smell of a thousand empty energy drinks",
  "uncontrollable, involuntary mewing",
  "a Labubu with dead, knowing eyes",
  "a slowly melting Grimace shake",
  "an AI girlfriend named after a Roblox character",
  "57 unwashed gaming chairs",
  "one single, perfect rizz",
  "the entire Costco free sample table",
  "my looksmaxxing surgeon's invoice",
  "a mason jar of room-temperature pre-workout",
  "the Rizzler himself",
  "Baby Gronk's NIL deal",
  "an aura reading of negative ten thousand",
  "the Hawk Tuah girl",
  "a deeply concerning Quandale Dingle situation",
  "John Pork, calling at 3 a.m.",
  "the entire unpaid Discord mod team",
  "freshly downloaded, government-grade brain rot",
  "the mitochondria, the powerhouse of the cell",
  "an RGB-lit shame closet",
  "a keyboard that crunches when you type",
  "the ick, weaponized",
  "an unspeakable quantity of Monster Energy",
  "ratio + L + you fell off",
  "touching grass for the very first time",
  "Ohio rizz",
  "the GYATT singularity",
  "a 900-day Duolingo streak held hostage",
  "my parasocial relationship with a VTuber",
  "the algorithm itself",
  "a $49.99 'escape the matrix' course",
  "my deeply unwell search history",
  "the void where my dopamine used to be",
  "a 12-hour Minecraft parkour video with no audio",
  "skibidi rizz with maximum Ohio aura",
  "a forklift certification I'll never use",
  "the W my mom said I'd never get",
  "an emotional support energy drink",
  "the last functioning brain cell in the group chat",
  "a tactical Pokémon card reseller",
  "absolutely zero bitches",
  "a suspicious amount of confidence and no plan",
  "the gooncave thermostat set to 'sauna'",
  "a Twitch streamer mid-meltdown",
  "the rizzly bear",
  "a chronically online uncle",
  "negative aura, but make it fashion",
  "an unhinged 4 a.m. grindset journal entry",
  "the forbidden second monitor",
  "a girl who's never heard the word 'gooncave'",
  "my untreated, unsupervised dopamine deficiency",
  "a single sock and a dream",
  "the entire bottom shelf of the gas station cooler",
  "a haunted, sentient gaming setup",
  "the manosphere starter pack",
  "a motivational quote stolen from a movie villain",
  "the smell of victory and Doritos dust",
  "a fully unionized colony of feral raccoons",
  "the cringe I will never live down",
  "an inheritance spent entirely on loot boxes",
  "a podcast bro who 'just thinks logically'",
  "the audacity of a man with zero rizz",
  "an unread stack of self-help books",
  "the Wi-Fi password to enlightenment",
  "a perfectly normal amount of obsession (it is not)",
  "the looksmaxxing before-and-after that's just lighting",
  "an army of NPCs who all walk into the same wall",
  "a goblin in a hoodie",
  "the lake house, but it's flooded with Mountain Dew",
  "a canoe full of regret",
  "the dock where I lost my last shred of dignity",
  "skinny dipping at the worst possible time",
  "a deeply cursed s'more",
  "the lake monster everyone pretends isn't real",
  "a jet ski I cannot afford and cannot drive",
  "the in-laws arriving two days early",
  "a screaming loon at 4 a.m.",
  "an inflatable flamingo with too much attitude",
  "the group chat planning a trip that will never happen",
  "wet socks for the entire weekend",
  "a tackle box full of bad decisions",
  "the one mosquito that ruins everything",
  "grandma's terrifyingly competitive card game face",
  "a cooler containing only mustard",
  "the bonfire that got slightly out of hand",
  "a paddleboard yoga influencer",
  "the cabin's haunted board game",
  "a fish that maintained eye contact",
  "the 'fun' family hike from hell",
  "an overconfident kayak flip",
  "a sunburn shaped like regret",
  "the neighbor's suspiciously loud generator",
  "a raccoon that learned to open the cooler",
  "the lake water you definitely shouldn't swallow",
  "an unhinged amount of bug spray",
  "the dad who insists he 'knows a shortcut'",
  "a banana boat ride gone deeply wrong",
  "the campfire story that traumatized the kids",
  "a dock plank that gives everyone splinters",
  "the smug confidence of a man with no sunscreen",
  "a goose with a personal vendetta",
  "the 'quick' five-hour fishing trip",
  "an entire weekend of competitive pontoon energy",
  "the floatie that drifted into the next county",
  "a suspiciously damp deck of cards",
  "the s'mores-to-mosquito-bite ratio",
  "an aggressively patriotic speedboat",
  "the cabin's single, judgmental cat",
  "a thermos of unidentifiable lake-house punch",
  "the family member who 'doesn't do board games'",
  "a beanbag toss rivalry that ended a friendship",
  "the dock cannonball that emptied the lake",
  "a tan line shaped like a phone",
  "an emotionally complex pontoon boat",
  "the kayak that betrayed me",
];

// Bonus deck: "Lake House Truths" — cozy + chaotic prompts to read aloud and answer.
export const LAKE_TRUTHS = [
  { type: "Would You Rather", text: "Would you rather spend the whole weekend with no Wi-Fi, or no hot water?" },
  { type: "Would You Rather", text: "Would you rather fall off the dock fully clothed, or get caught singing to yourself in the kayak?" },
  { type: "Would You Rather", text: "Would you rather share a bunk bed with a snorer, or a sleep-talker who narrates dreams?" },
  { type: "Would You Rather", text: "Would you rather always be the one who packs the snacks, or always be the one who drives?" },
  { type: "Would You Rather", text: "Would you rather swim across the whole lake, or run the entire shoreline trail?" },
  { type: "Would You Rather", text: "Would you rather win every card game but lose every fishing contest, or vice versa?" },
  { type: "Never Have I Ever", text: "Never have I ever capsized a canoe on purpose." },
  { type: "Never Have I Ever", text: "Never have I ever pretended to know how to start the boat." },
  { type: "Never Have I Ever", text: "Never have I ever eaten a s'more that was 90% marshmallow goo." },
  { type: "Never Have I Ever", text: "Never have I ever 'accidentally' splashed someone who deserved it." },
  { type: "Never Have I Ever", text: "Never have I ever lost a flip-flop to the lake forever." },
  { type: "Truth", text: "What's the most chaotic thing that's ever happened on a family trip?" },
  { type: "Truth", text: "Who in this group would survive longest stranded on the lake's tiny island?" },
  { type: "Truth", text: "What's your most embarrassing 'outdoorsy' fail?" },
  { type: "Truth", text: "If the cabin were haunted, whose fault would it be?" },
  { type: "Dare", text: "Do your best loon call. Loudly. Right now." },
  { type: "Dare", text: "Narrate the next 60 seconds like a nature documentary." },
  { type: "Dare", text: "Give a dramatic toast to the lake as if you'll never see it again." },
  { type: "Dare", text: "Convince everyone you caught a fish 'this big' with a straight face." },
  { type: "Most Likely To", text: "Who's most likely to fall asleep in the hammock and miss dinner?" },
  { type: "Most Likely To", text: "Who's most likely to start a competitive feud over a board game?" },
  { type: "Most Likely To", text: "Who's most likely to befriend the lake's resident goose?" },
  { type: "Most Likely To", text: "Who's most likely to 'just check work email' on vacation?" },
];
