// Card data for the Lake House card games.
// Cards Against Monkeys: an adult party game. Prompts (black) + responses (white).

// Blank marker used in prompt text. The UI replaces these with the chosen card(s).
export const BLANK = "_______";

// Prompt cards. `pick` = how many response cards must be played.
// Prompts written as questions have no blank and the answer is shown beneath.
export const PROMPTS = [
  // --- Pick One ---
  { text: `Welcome to my gooncave. Please ignore the LED lights, the smell, and the massive shrine dedicated to ${BLANK}.`, pick: 1 },
  { text: `I just lost my 400-day edging streak because I accidentally caught a glimpse of ${BLANK}.`, pick: 1 },
  { text: `To achieve the ultimate sigma male grindset, you must supplement your daily mewing routine with ${BLANK}.`, pick: 1 },
  { text: `What is the absolute necessary centerpiece of any respectable, multi-monitor gooncave?`, pick: 1 },
  { text: `Bro couldn't handle the marathon gooning session. He took one look at ${BLANK} and completely tapped out.`, pick: 1 },
  { text: `The TikTok rizz party was completely ruined when the host confidently brought out ${BLANK}.`, pick: 1 },
  { text: `My therapist said my crippling, chronic addiction to ${BLANK} is preventing me from becoming a true alpha.`, pick: 1 },
  { text: `"I literally can't goon to this! Where is the ${BLANK}?!"`, pick: 1 },
  { text: `They permanently banned me from the Discord server because my primary gooning material was literally just ${BLANK}.`, pick: 1 },
  { text: `Looksmaxxing is out. The new trend is improving your jawline by constantly chewing on ${BLANK}.`, pick: 1 },
  { text: `The group chat got completely silent after I dropped a 4K image of ${BLANK}.`, pick: 1 },
  { text: `What's the only thing that can distract me during a highly focused, six-hour edging marathon?`, pick: 1 },

  // --- Pick Two ---
  { text: `You call yourself a goon commander? You can't even edge to ${BLANK} without immediately thinking about ${BLANK}.`, pick: 2 },
  { text: `I entered the gooncave expecting ${BLANK}, but all I found was an ultrawide monitor displaying ${BLANK}.`, pick: 2 },
  { text: `The only thing standing between me and my ultimate looksmaxxing goals is ${BLANK} and a severe lack of ${BLANK}.`, pick: 2 },
  { text: `My absolute peak brain-rot setup requires three monitors: one for Subway Surfers gameplay, one for ${BLANK}, and one for ${BLANK}.`, pick: 2 },
  { text: `Instead of an intervention, my friends sat me down and tried to replace my addiction to ${BLANK} with ${BLANK}.`, pick: 2 },
  { text: `Forget astrology signs. Are you more of a ${BLANK} male, or a ${BLANK} male?`, pick: 2 },
  { text: `I'm not just a gooner, I'm an innovator. I've discovered a way to combine ${BLANK} with ${BLANK} for maximum brain-rot.`, pick: 2 },

  // --- Pick One (zesty/sussy expansion) ---
  { text: `I knew bro was the impostor because he was acting way too zesty while ${BLANK}.`, pick: 1 },
  { text: `When the level 100 Discord mod calls you his "little sussy baka," the only appropriate response is ${BLANK}.`, pick: 1 },
  { text: `Bro couldn't survive one night in Ohio because he got caught doing the absolute zestiest ${BLANK}.`, pick: 1 },
  { text: `Emergency meeting! I just saw Red venting, and honestly, they looked incredibly zesty while holding ${BLANK}.`, pick: 1 },
  { text: `I'm not a sussy baka, I swear! I was just in electrical doing a little dance with ${BLANK}.`, pick: 1 },
  { text: `The TikTok rizz party was immediately shut down when someone hit the most zesty ${BLANK} known to mankind.`, pick: 1 },
  { text: `You can't call yourself a true gooner if your primary screen is just a 10-hour loop of ${BLANK}.`, pick: 1 },
  { text: `Drake's new album features a 12-minute interlude where he just zestily whispers about ${BLANK}.`, pick: 1 },
  { text: `They caught me being a sussy baka in 4K. My only defense in court was ${BLANK}.`, pick: 1 },
  { text: `What's the absolute zestiest thing you could possibly bring to a serious goon session?`, pick: 1 },
  { text: `It's impossible to maintain your sigma grindset when the group chat keeps sending you ${BLANK}.`, pick: 1 },
  { text: `Bro thought he had that W rizz, but honestly, it just gave off massive ${BLANK} energy.`, pick: 1 },

  // --- Pick Two (zesty/sussy expansion) ---
  { text: `First I hit 'em with the zesty ${BLANK}, then I follow it up with a sussy ${BLANK}.`, pick: 2 },
  { text: `Forget the impostor. The real threat to this spaceship is ${BLANK} combined with ${BLANK}.`, pick: 2 },
  { text: `You can't be a true goon commander if you let a sussy baka distract you with ${BLANK} and ${BLANK}.`, pick: 2 },
  { text: `My ultra-zesty morning routine involves waking up, doing a little dance, and immediately interacting with ${BLANK} and ${BLANK}.`, pick: 2 },
  { text: `I entered the chat expecting some W rizz, but instead, I was hit with a profoundly sussy ${BLANK} and an even zestier ${BLANK}.`, pick: 2 },
  { text: `Listen, if you survive the Fanum tax, the only things left to worry about are ${BLANK} and ${BLANK}.`, pick: 2 },
  { text: `The judge sentenced him to 100 hours of community service for combining a zesty ${BLANK} with a completely unhinged ${BLANK}.`, pick: 2 },
];

// Response cards — chronically-online brain-rot answers.
export const RESPONSES = [
  "Subway Surfers gameplay",
  "an unskippable 4K Skibidi Toilet cutscene",
  "the Ohio final boss",
  "my completely untouched gym membership",
  "an aggressive Fanum tax",
  "raw, uncut sigma male grindset",
  "a GYATT of unimaginable proportions",
  "the smell of a thousand empty energy drinks",
  "uncontrollable, involuntary mewing",
  "a Labubu with dead, knowing eyes",
  "a slowly melting Grimace shake",
  "an AI girlfriend named after a Roblox character",
  "57 unwashed gaming chairs",
  "one single, perfect rizz",
  "the entire Costco free sample table",
  "my looksmaxxing surgeon's invoice",
  "a mason jar of room-temperature pre-workout",
  "the Rizzler himself",
  "Baby Gronk's NIL deal",
  "an aura reading of negative ten thousand",
  "the Hawk Tuah girl",
  "a deeply concerning Quandale Dingle situation",
  "John Pork, calling at 3 a.m.",
  "the entire unpaid Discord mod team",
  "freshly downloaded, government-grade brain rot",
  "the mitochondria, the powerhouse of the cell",
  "an RGB-lit shame closet",
  "a keyboard that crunches when you type",
  "the ick, weaponized",
  "an unspeakable quantity of Monster Energy",
  "ratio + L + you fell off",
  "touching grass for the very first time",
  "Ohio rizz",
  "the GYATT singularity",
  "a 900-day Duolingo streak held hostage",
  "my parasocial relationship with a VTuber",
  "the algorithm itself",
  "a $49.99 'escape the matrix' course",
  "my deeply unwell search history",
  "the void where my dopamine used to be",
  "a 12-hour Minecraft parkour video with no audio",
  "skibidi rizz with maximum Ohio aura",
  "a forklift certification I'll never use",
  "the W my mom said I'd never get",
  "an emotional support energy drink",
  "the last functioning brain cell in the group chat",
  "a tactical Pokémon card reseller",
  "absolutely zero bitches",
  "a suspicious amount of confidence and no plan",
  "the gooncave thermostat set to 'sauna'",
  "a Twitch streamer mid-meltdown",
  "the rizzly bear",
  "a chronically online uncle",
  "negative aura, but make it fashion",
  "an unhinged 4 a.m. grindset journal entry",
  "the forbidden second monitor",
  "a girl who's never heard the word 'gooncave'",
  "my untreated, unsupervised dopamine deficiency",
  "a single sock and a dream",
  "the entire bottom shelf of the gas station cooler",
  "a haunted, sentient gaming setup",
  "the manosphere starter pack",
  "a motivational quote stolen from a movie villain",
  "the smell of victory and Doritos dust",
  "a fully unionized colony of feral raccoons",
  "the cringe I will never live down",
  "an inheritance spent entirely on loot boxes",
  "a podcast bro who 'just thinks logically'",
  "the audacity of a man with zero rizz",
  "an unread stack of self-help books",
  "the Wi-Fi password to enlightenment",
  "a perfectly normal amount of obsession (it is not)",
  "the looksmaxxing before-and-after that's just lighting",
  "an army of NPCs who all walk into the same wall",
  "a goblin in a hoodie",
  "the lake house, but it's flooded with Mountain Dew",
  "a canoe full of regret",
  "the dock where I lost my last shred of dignity",
  "skinny dipping at the worst possible time",
  "a deeply cursed s'more",
  "the lake monster everyone pretends isn't real",
  "a jet ski I cannot afford and cannot drive",
  "the in-laws arriving two days early",
  "a screaming loon at 4 a.m.",
  "an inflatable flamingo with too much attitude",
  "the group chat planning a trip that will never happen",
  "wet socks for the entire weekend",
  "a tackle box full of bad decisions",
  "the one mosquito that ruins everything",
  "grandma's terrifyingly competitive card game face",
  "a cooler containing only mustard",
  "the bonfire that got slightly out of hand",
  "a paddleboard yoga influencer",
  "the cabin's haunted board game",
  "a fish that maintained eye contact",
  "the 'fun' family hike from hell",
  "an overconfident kayak flip",
  "a sunburn shaped like regret",
  "the neighbor's suspiciously loud generator",
  "a raccoon that learned to open the cooler",
  "the lake water you definitely shouldn't swallow",
  "an unhinged amount of bug spray",
  "the dad who insists he 'knows a shortcut'",
  "a banana boat ride gone deeply wrong",
  "the campfire story that traumatized the kids",
  "a dock plank that gives everyone splinters",
  "the smug confidence of a man with no sunscreen",
  "a goose with a personal vendetta",
  "the 'quick' five-hour fishing trip",
  "an entire weekend of competitive pontoon energy",
  "the floatie that drifted into the next county",
  "a suspiciously damp deck of cards",
  "the s'mores-to-mosquito-bite ratio",
  "an aggressively patriotic speedboat",
  "the cabin's single, judgmental cat",
  "a thermos of unidentifiable lake-house punch",
  "the family member who 'doesn't do board games'",
  "a beanbag toss rivalry that ended a friendship",
  "the dock cannonball that emptied the lake",
  "a tan line shaped like a phone",
  "an emotionally complex pontoon boat",
  "the kayak that betrayed me",
  // zesty / sussy / Among Us / Drake expansion
  "Red, venting in broad daylight",
  "a little zesty dance in electrical",
  "the emergency meeting button, slammed for no reason",
  "a task I 100% faked and self-reported",
  "0.5 impostors remaining",
  "getting ejected (he was NOT the impostor)",
  "a level 100 Discord mod's 'little baka' voice memo",
  "the sussiest baka in the entire lobby",
  "an unskippable 12-minute Drake interlude",
  "Drake whispering zestily about absolutely nothing",
  "a certified hood classic nobody asked for",
  "the Fanum tax collector knocking at 3 a.m.",
  "a perfectly cut scream",
  "the 'he's literally me' starter pack",
  "a 10-hour loop of the Subway Surfers victory wrap",
  "the gyatt that triggered an emergency meeting",
  "an aggressively zesty morning routine",
  "doing a little dance and immediately regretting it",
  "the impostor who was suspiciously good at electrical",
  "a sus amount of eye contact",
  "the W that was actually a profound L",
  "maximum sus, minimum rizz",
  "an unhinged amount of zest",
  "a baka so sussy it broke the lobby",
  "the vent nobody saw me climb out of",
  "a 4K replay of me being mid",
  "the group chat sending the same TikTok 40 times",
  "a wildly misplaced 'certified lover boy' caption",
  "the airlock, opening at the worst possible time",
  "a crewmate doing tasks suspiciously well",
  "the zesty whisper that ended a friendship",
  "an emotional support emergency meeting",
  "the cafeteria, where it all went down",
  "a fake task that fooled absolutely no one",
  "the silence after I said 'it's giving impostor'",
  "a Drake reaction GIF used as legal evidence",
  "the lobby's collective lack of object permanence",
  "a guy named Red who SWEARS he's innocent",
  "the most zesty thing known to mankind",
  "an unprompted sigma walk-out",
  "the ick, but make it sussy",
  "a 'trust me bro' with zero sources",
  "the brain-rot horizon, expanding daily",
  "an NPC who only says 'sus' and 'zesty'",
  "the ultimate rizz that turned into an L speedrun",
  "a deeply suspicious amount of vibe",
];

// Bonus deck: "Lake House Truths" — cozy + chaotic prompts to read aloud and answer.
export const LAKE_TRUTHS = [
  { type: "Would You Rather", text: "Would you rather spend the whole weekend with no Wi-Fi, or no hot water?" },
  { type: "Would You Rather", text: "Would you rather fall off the dock fully clothed, or get caught singing to yourself in the kayak?" },
  { type: "Would You Rather", text: "Would you rather share a bunk bed with a snorer, or a sleep-talker who narrates dreams?" },
  { type: "Would You Rather", text: "Would you rather always be the one who packs the snacks, or always be the one who drives?" },
  { type: "Would You Rather", text: "Would you rather swim across the whole lake, or run the entire shoreline trail?" },
  { type: "Would You Rather", text: "Would you rather win every card game but lose every fishing contest, or vice versa?" },
  { type: "Never Have I Ever", text: "Never have I ever capsized a canoe on purpose." },
  { type: "Never Have I Ever", text: "Never have I ever pretended to know how to start the boat." },
  { type: "Never Have I Ever", text: "Never have I ever eaten a s'more that was 90% marshmallow goo." },
  { type: "Never Have I Ever", text: "Never have I ever 'accidentally' splashed someone who deserved it." },
  { type: "Never Have I Ever", text: "Never have I ever lost a flip-flop to the lake forever." },
  { type: "Truth", text: "What's the most chaotic thing that's ever happened on a family trip?" },
  { type: "Truth", text: "Who in this group would survive longest stranded on the lake's tiny island?" },
  { type: "Truth", text: "What's your most embarrassing 'outdoorsy' fail?" },
  { type: "Truth", text: "If the cabin were haunted, whose fault would it be?" },
  { type: "Dare", text: "Do your best loon call. Loudly. Right now." },
  { type: "Dare", text: "Narrate the next 60 seconds like a nature documentary." },
  { type: "Dare", text: "Give a dramatic toast to the lake as if you'll never see it again." },
  { type: "Dare", text: "Convince everyone you caught a fish 'this big' with a straight face." },
  { type: "Most Likely To", text: "Who's most likely to fall asleep in the hammock and miss dinner?" },
  { type: "Most Likely To", text: "Who's most likely to start a competitive feud over a board game?" },
  { type: "Most Likely To", text: "Who's most likely to befriend the lake's resident goose?" },
  { type: "Most Likely To", text: "Who's most likely to 'just check work email' on vacation?" },
];

// Would You Rather: Unhinged — chronically-online dilemmas. Read both, everyone votes.
export const WOULD_YOU_RATHER = [
  { tag: "Would You Rather", text: "Lose your entire 400-day streak, or have the group chat read your search history out loud?" },
  { tag: "Would You Rather", text: "Get caught venting in 4K, or get Fanum-taxed every single meal for a year?" },
  { tag: "Would You Rather", text: "Only communicate in TikTok audios forever, or only in Drake lyrics forever?" },
  { tag: "Would You Rather", text: "Be the sussiest baka in every lobby, or the zestiest dancer in every electrical?" },
  { tag: "Would You Rather", text: "Have permanent W rizz but a -1000 aura, or perfect aura but the rizz of a damp sock?" },
  { tag: "Would You Rather", text: "Survive one night in Ohio, or one emergency meeting where everyone votes you out?" },
  { tag: "Would You Rather", text: "Have your jawline maxed but mew incorrectly forever, or perfect mewing and a chin like a melted candle?" },
  { tag: "Would You Rather", text: "Be looped into a 10-hour Subway Surfers stream, or a 12-minute Drake whisper interlude on repeat?" },
  { tag: "Would You Rather", text: "Be known forever as 'the impostor', or forever as 'the little sussy baka'?" },
  { tag: "Would You Rather", text: "Never touch grass again, or never touch your phone again?" },
  { tag: "Would You Rather", text: "Get rizzed up by an NPC, or ratio'd by your own grandma in the group chat?" },
  { tag: "Would You Rather", text: "Have a gyatt that triggers emergency meetings, or rizz that triggers second-hand embarrassment?" },
  { tag: "Would You Rather", text: "Win every argument but only in Ohio, or be right everywhere but nobody believes you?" },
  { tag: "Would You Rather", text: "Be sentenced to 100 hours of cringe community service, or 100 hours of forced grindset content?" },
  { tag: "Would You Rather", text: "Have everything you say auto-tuned by Drake, or auto-captioned as 'sus'?" },
  { tag: "Would You Rather", text: "Be the level 100 Discord mod nobody respects, or the new guy everyone calls 'baka'?" },
  { tag: "Would You Rather", text: "Get the W but it's the zestiest W imaginable, or take the L with maximum aura intact?" },
  { tag: "Would You Rather", text: "Only goon-cave lighting for the rest of your life, or only fluorescent gas-station lighting?" },
];

// Red Flag / Green Flag — read a trait aloud, group debates and shouts the verdict.
export const RED_GREEN = [
  { tag: "Red or Green?", text: "Their entire personality is one TikTok audio." },
  { tag: "Red or Green?", text: "Refers to their bedroom, unironically, as 'the goon cave'." },
  { tag: "Red or Green?", text: "Calls everyone 'little sussy baka', including their boss." },
  { tag: "Red or Green?", text: "Has a 400-day streak of something they refuse to explain." },
  { tag: "Red or Green?", text: "Hits the emergency meeting button over the smallest inconvenience." },
  { tag: "Red or Green?", text: "Mews in the middle of the conversation and expects you not to notice." },
  { tag: "Red or Green?", text: "Sends 40 identical TikToks and then says 'you up?'" },
  { tag: "Red or Green?", text: "Their love language is Fanum-taxing your fries." },
  { tag: "Red or Green?", text: "Claims a -1000 aura reading like it's a flex." },
  { tag: "Red or Green?", text: "Does a little zesty dance before every important decision." },
  { tag: "Red or Green?", text: "Will not stop quoting Drake during a breakup." },
  { tag: "Red or Green?", text: "Maxed their jawline but lost the ability to make eye contact." },
  { tag: "Red or Green?", text: "Self-reports their own tasks and acts shocked when ejected." },
  { tag: "Red or Green?", text: "Owns a single sock and calls it 'the setup'." },
  { tag: "Red or Green?", text: "Brings up their sigma grindset at a funeral." },
  { tag: "Red or Green?", text: "Has an AI girlfriend AND is jealous of her." },
  { tag: "Red or Green?", text: "Touches grass exactly once and posts a 9-slide carousel about it." },
  { tag: "Red or Green?", text: "Negotiates the Fanum tax with a signed contract." },
  { tag: "Red or Green?", text: "Whispers 'it's giving impostor' at every party." },
  { tag: "Red or Green?", text: "Three monitors, one is exclusively for Subway Surfers." },
  { tag: "Red or Green?", text: "Says 'trust me bro' and is somehow always wrong." },
  { tag: "Red or Green?", text: "Replaces 'I love you' with 'you got that W rizz'." },
];

// Most Likely To — used by Emergency Meeting (voting game).
export const MOST_LIKELY = [
  "get voted off the spaceship first, fairly",
  "be the actual impostor and get away with it",
  "lose a 400-day streak to a single notification",
  "start an emergency meeting over literally nothing",
  "have the most cursed search history in the room",
  "call their crush 'little sussy baka' out loud",
  "fake all their tasks and self-report with confidence",
  "do a zesty little dance at the worst possible moment",
  "get Fanum-taxed and say thank you",
  "claim a -1000 aura reading as a personality trait",
  "fall for an obvious 'trust me bro'",
  "quote Drake during an actual emergency",
  "mew through an entire serious conversation",
  "survive the longest stranded in Ohio",
  "turn a guaranteed W into a speedrun L",
  "get caught being sus in 4K",
  "have three monitors and accomplish nothing",
  "become a level 100 Discord mod and abuse it",
  "vent in front of everyone and act innocent",
  "send the same TikTok to the group chat 40 times",
  "touch grass and immediately post about it",
  "rizz up an NPC and get rejected",
  "defend their goon cave in a court of law",
  "be the reason the group chat got muted",
];
