// Dedicated TV Host & Spectator presentation board for living-room screens.
import { el, mount, toast } from "./ui.js";
import { icons } from "./icons.js";
import { renderDiceFaceSVG, playClickTone } from "./games/dice_hub.js";

const WS_BASE = location.hostname === "localhost" || location.hostname === "127.0.0.1"
  ? "ws://localhost:3000"
  : "wss://lakehouse-cardgames-sync.gameassassin777.workers.dev";

const HTTP_BASE = location.hostname === "localhost" || location.hostname === "127.0.0.1"
  ? "http://localhost:3000"
  : "https://lakehouse-cardgames-sync.gameassassin777.workers.dev";

let goHome = () => {};
let socket = null;
let roomCode = "";
let activeGameId = "";
let heartbeatInt = null;

let gState = null;
let revealedPlayers = null; // Used for Liar's Dice challenge reveals

export function start(home) {
  goHome = home;
  renderTVConnectScreen();
}

function resetAll() {
  if (socket) { try { socket.close(); } catch (_) {} socket = null; }
  if (heartbeatInt) { clearInterval(heartbeatInt); heartbeatInt = null; }
  roomCode = ""; activeGameId = ""; gState = null; revealedPlayers = null;
}

function tvTopbar(title, onBack) {
  return el("div", { className: "topbar" }, [
    el("button", { className: "back", onClick: onBack }, [
      el("span", { style: "width:16px; height:16px; display:inline-block;" }, [icons.back()]),
      el("span", { text: "Exit" })
    ]),
    el("div", { className: "title", text: title }),
    el("span", { style: "width:64px" })
  ]);
}

function renderTVConnectScreen() {
  resetAll();

  const codeInput = el("input", {
    type: "text",
    placeholder: "4-LETTER CODE",
    id: "tv-room-code",
    maxLength: 4,
    style: "font-size:2rem; font-weight:bold; border-radius:16px; text-align:center; text-transform:uppercase; letter-spacing:8px; margin:20px 0 16px; width:100%; height:60px;"
  });
  codeInput.addEventListener("input", () => { codeInput.value = codeInput.value.toUpperCase(); });

  const connectBtn = el("button", {
    className: "btn",
    text: "📺 Launch TV Broadcast Screen",
    style: "width:100%; font-size:1.1rem; padding:14px; font-weight:bold;",
    onClick: () => {
      const code = codeInput.value.trim().toUpperCase();
      if (!code || code.length !== 4) { toast("Enter a valid 4-letter room code!"); return; }
      connectAsTV(code);
    }
  });

  mount(
    tvTopbar("TV Screen Broadcast Setup", goHome),
    el("div", { className: "panel center", style: "max-width: 480px; margin: 40px auto; padding: 24px;" }, [
      el("span", { style: "font-size:3.5rem; line-height:1; display:inline-block; margin-bottom:12px;" }, [document.createTextNode("📺")]),
      el("h2", { text: "TV Broadcast Screen", style: "margin:0 0 6px;" }),
      el("p", { className: "muted", text: "Open this page on your laptop, iPad, or smart TV. Enter the 4-letter room code generated by any mobile host to launch a grand, living-room optimized spectator board." }),
      codeInput,
      connectBtn
    ])
  );
}

function connectAsTV(code) {
  roomCode = code;
  mount(
    tvTopbar("Connecting TV Screen", () => renderTVConnectScreen()),
    el("div", { className: "panel center", style: "margin:40px auto; max-width:360px;" }, [
      el("div", { className: "spin-indicator", style: "font-size:2.5rem; margin-bottom:16px;", text: "🌀" }),
      el("p", { text: `Connecting to Room: ${code}…`, style: "font-weight:bold;" })
    ])
  );

  // We connect with the reserved spectator name '__TV__'
  const url = `${WS_BASE}/ws/join?code=${code}&name=__TV__&game=tv_spectator`;
  socket = new WebSocket(url);

  socket.onmessage = (ev) => {
    try {
      const d = JSON.parse(ev.data);
      if (d.type === "created" || d.type === "player_joined" || d.type === "player_left") {
        renderLobbyView(d.players);
      } else if (d.type === "relay") {
        handleTVRelay(d.action, d.sender);
      } else if (d.type === "error") {
        toast(d.message || "Spectator connection error");
        renderTVConnectScreen();
      }
    } catch (e) {
      console.error("[TV Host] message parsing exception:", e);
    }
  };

  socket.onclose = () => {
    stopHeartbeat();
    toast("TV disconnected from room.");
    renderTVConnectScreen();
  };
}

function stopHeartbeat() {
  if (heartbeatInt) { clearInterval(heartbeatInt); heartbeatInt = null; }
}

function startTVHeartbeat(playersList) {
  stopHeartbeat();
  const ping = () => fetch(`${HTTP_BASE}/rooms/heartbeat`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ code: roomCode, playerCount: playersList.length || 1 })
  }).catch(() => {});
  ping();
  heartbeatInt = setInterval(ping, 25000);
}

function renderLobbyView(playersList) {
  // Filter spectator names
  const activePlayers = playersList.filter(p => p !== "__TV__");
  startTVHeartbeat(playersList);

  const pBadges = activePlayers.map(p => {
    return el("div", {
      className: "panel center",
      style: "padding: 14px 20px; font-size:1.15rem; font-weight:bold; background:rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.06); border-radius:14px; color: var(--sunset-soft);"
    }, [document.createTextNode(p)]);
  });

  const lobbyGrid = el("div", {
    style: "display:grid; grid-template-columns: repeat(auto-fill, minmax(130px, 1fr)); gap:12px; width:100%; margin-top:20px;"
  }, pBadges);

  mount(
    tvTopbar(`TV Screen Lobby: ${roomCode}`, () => renderTVConnectScreen()),
    el("div", { className: "panel center", style: "max-width:700px; margin: 40px auto; padding: 24px;" }, [
      el("h1", { text: "Lobby Sync Active", style: "margin-top:0; color:#00ffaa;" }),
      el("p", { className: "muted", style: "font-size:1.1rem;", text: `TV Screen successfully joined room code: ${roomCode}. Join on your phones as players and start the game when ready!` }),
      activePlayers.length > 0 ? el("label", { text: `Connected Players (${activePlayers.length})` }) : el("label", { text: "Waiting for players to connect..." }),
      lobbyGrid
    ])
  );
}

function handleTVRelay(action, sender) {
  // Auto-detect game state payloads
  if (action.state) {
    gState = action.state;
  }

  // Quiplash broadcasts
  if (action.type === "quiplash_state") {
    gState = action.state;
    renderQuiplashTV(gState);
  }
  // Liar's Dice broadcasts
  else if (action.type === "start_game" && sender !== "__TV__") {
    gState = { phase: "play", players: action.players };
  } else if (action.type === "start_round" && action.diceMap) {
    gState = action.state;
    // Mirror standard rolls
    renderLiarsDiceTV(gState);
  } else if (action.type === "place_bid") {
    if (gState) {
      gState.currentBid = action.bid;
      gState.activePlayerIdx = action.nextPlayerIdx;
      playClickTone(600, 0.08);
      renderLiarsDiceTV(gState);
    }
  } else if (action.type === "resolve_challenge") {
    revealedPlayers = action.revealedPlayers;
    renderLiarsDiceRevealTV(action);
  }
  // Farkle broadcasts
  else if (action.type === "state_update" && gState) {
    gState = action.state;
    renderFarkleTV(gState);
  } else if (action.type === "trigger_roll") {
    // Shaking rolling animation on the TV screen!
    triggerTVRollAnimation(action.diceValues);
  }
  // Generic deck games & cards syncs
  else if (action.type === "STATE_SYNC") {
    gState = action.state;
    renderCardsTV(gState);
  } else if (action.type === "quit") {
    toast("Game closed by host.");
    renderTVConnectScreen();
  }
}

// ── 1. Quiplash TV presentation View ───────────────────────────────────────────
function renderQuiplashTV(state) {
  // If lobby phase, show players
  if (state.phase === "lobby") {
    renderLobbyView(state.players);
    return;
  }

  const promptCard = el("div", {
    className: "play-card prompt",
    style: "font-size:2rem; min-height:120px; line-height:1.3; text-align:center; justify-content:center; padding:20px; margin-bottom:24px;"
  }, [el("span", { text: state.prompt || "Quiplash Prompt!" })]);

  // If matchup battle phase, show the two answers side-by-side
  let matchupEl = null;
  if (state.phase === "battle") {
    matchupEl = el("div", {
      style: "display:flex; gap:20px; width:100%; margin-top:20px;"
    }, [
      el("div", {
        className: "panel center",
        style: "flex:1; padding:24px; border:2px solid rgba(255,255,255,0.06); background:rgba(255,145,100,0.03); border-radius:18px;"
      }, [
        el("p", { className: "muted", text: "ANSWER A", style: "font-size:0.8rem; letter-spacing:1px; margin:0 0 8px;" }),
        el("h2", { text: state.answerA || "???", style: "margin:0; font-size:1.6rem; color:#ff9164;" })
      ]),
      el("div", {
        className: "panel center",
        style: "flex:1; padding:24px; border:2px solid rgba(255,255,255,0.06); background:rgba(100,180,255,0.03); border-radius:18px;"
      }, [
        el("p", { className: "muted", text: "ANSWER B", style: "font-size:0.8rem; letter-spacing:1px; margin:0 0 8px;" }),
        el("h2", { text: state.answerB || "???", style: "margin:0; font-size:1.6rem; color:#64b4ff;" })
      ])
    ]);
  } else if (state.phase === "writing") {
    matchupEl = el("div", { className: "panel center anim-pulse", style: "padding:20px; margin-top:20px;" }, [
      el("span", { style: "font-size:2.5rem;", text: "✍️" }),
      el("h3", { text: "Players are secretly typing answers...", style: "margin:8px 0 0;" })
    ]);
  } else if (state.phase === "standings") {
    const list = state.players.map((p, i) => {
      return el("div", {
        style: "display:flex; justify-content:space-between; align-items:center; padding:10px 16px; background:rgba(255,255,255,0.02); border-radius:12px; margin-bottom:8px;"
      }, [
        el("h3", { text: `${i + 1}. ${p.name}`, style: "margin:0;" }),
        el("span", { text: `${p.score} pts`, style: "font-size:1.3rem; font-weight:bold; color:var(--sunset-soft);" })
      ]);
    });
    matchupEl = el("div", { style: "width:100%; text-align:left; margin-top:20px;" }, [
      el("h2", { text: "Current Leaderboard", style: "text-align:center; color:#00ffaa; margin-bottom:16px;" }),
      ...list
    ]);
  }

  mount(
    tvTopbar(`Quiplash TV Board: Room ${roomCode}`, () => renderTVConnectScreen()),
    el("div", { className: "panel center", style: "max-width:800px; margin:0 auto; padding:24px;" }, [
      promptCard,
      matchupEl
    ])
  );
}

// ── 2. Liar's Dice TV presentation View ───────────────────────────────────────
function renderLiarsDiceTV(state) {
  let bidDisplay = el("h2", { text: "No active bids. Starting the bidding cycle!", className: "muted center" });
  if (state.currentBid) {
    const curDieSVG = renderDiceFaceSVG(state.currentBid.face);
    curDieSVG.style.width = "40px";
    curDieSVG.style.height = "40px";
    curDieSVG.style.display = "inline-block";
    curDieSVG.style.verticalAlign = "middle";
    curDieSVG.style.marginLeft = "8px";

    bidDisplay = el("div", {
      className: "panel center",
      style: "border: 2px solid var(--sunset-soft); background:rgba(255,145,100,0.04); border-radius:16px; padding:24px; margin-bottom:24px;"
    }, [
      el("span", { text: "Active Bid on the Table: ", className: "muted", style: "font-size:0.95rem; text-transform:uppercase; letter-spacing:1px;" }),
      el("h1", { style: "margin: 8px 0 0; color: var(--sunset-soft); font-weight:900; font-size:2.4rem;" }, [
        document.createTextNode(`${state.currentBid.count} of `),
        curDieSVG,
        document.createTextNode(` (by ${state.currentBid.bidder})`)
      ])
    ]);
  }

  const activePlayer = state.players[state.activePlayerIdx];
  const activeLabel = el("div", {
    className: "handoff anim-pulse",
    style: "padding:16px; border-radius:16px; background:rgba(255,255,255,0.03); border:1px solid rgba(255,255,255,0.08); width:100%;"
  }, [
    el("span", { text: "Current Turn Action:", className: "muted", style: "font-size:0.8rem; text-transform:uppercase;" }),
    el("h2", { text: activePlayer ? activePlayer.name : "Waiting...", style: "margin:6px 0 0; font-size:2.2rem; color:#00ffaa;" })
  ]);

  const totalActiveDice = state.players.reduce((sum, pl) => sum + pl.diceCount, 0);

  mount(
    tvTopbar(`Liar's Dice TV Table: ${roomCode}`, () => renderTVConnectScreen()),
    el("div", { className: "panel center", style: "max-width:760px; margin:0 auto; padding:24px;" }, [
      el("p", { className: "muted", text: `Active dice currently in play: ${totalActiveDice}`, style: "font-size:1.05rem; font-weight:bold; margin-bottom:20px;" }),
      bidDisplay,
      activeLabel
    ])
  );
}

function renderLiarsDiceRevealTV(action) {
  const bid = gState.currentBid;
  const revealRows = [];

  action.revealedPlayers.forEach(pl => {
    if (pl.diceCount >= 0) {
      const cupWrap = el("div", { style: "display:flex; gap:8px; flex-wrap:wrap;" });
      pl.dice.forEach(val => {
        const isMatch = val === bid.face;
        const dFace = renderDiceFaceSVG(val, isMatch);
        const box = el("div", {
          style: `width: 44px; height: 44px; padding: 3px; background: ${isMatch ? "rgba(255,145,100,0.12)" : "rgba(255,255,255,0.01)"}; border: 1.5px solid ${isMatch ? "var(--sunset-soft)" : "rgba(255,255,255,0.08)"}; border-radius: 8px;`
        }, [dFace]);
        cupWrap.appendChild(box);
      });

      revealRows.push(el("div", {
        style: "display:flex; justify-content:space-between; align-items:center; padding:12px 20px; background:rgba(255,255,255,0.01); border-radius:14px; margin-bottom:10px; border:1px solid rgba(255,255,255,0.04);"
      }, [
        el("span", { text: pl.name, style: "font-weight: bold; font-size:1.1rem; color:var(--sunset-soft);" }),
        cupWrap
      ]));
    }
  });

  const didBidderWin = action.didBidderWin;
  const resultTitle = el("h1", {
    text: didBidderWin ? "Challenger Lost!" : "Bidder was a Liar!",
    style: `font-size:2.6rem; font-weight:900; color:${didBidderWin ? "#ff5e5e" : "#00ffaa"}; margin: 0 0 10px;`
  });

  let logResultText = didBidderWin
    ? `Enough! There were ${action.matchCount} matching 🎲${bid.face}s in the room (required at least ${bid.count}). ${action.loserName} loses a die!`
    : `Liar! There were only ${action.matchCount} matching 🎲${bid.face}s in the room (bid was ${bid.count}). ${action.loserName} loses a die!`;

  mount(
    tvTopbar(`Liar Challenge Reveal: ${roomCode}`, () => renderTVConnectScreen()),
    el("div", { className: "panel center", style: "max-width: 800px; margin: 0 auto; padding:24px;" }, [
      resultTitle,
      el("p", { className: "muted", text: logResultText, style: "font-size:1.25rem; margin-bottom:24px; line-height:1.4;" }),
      ...revealRows
    ])
  );
}

// ── 3. Farkle TV Scorecard Broadcast View ─────────────────────────────────────
function renderFarkleTV(state) {
  const players = state.players;
  const states = state.states;
  const activeIdx = state.activePlayerIdx;
  const activePlayerName = players[activeIdx];
  const activeState = states[activeIdx];

  const playerBlocks = players.map((name, pIdx) => {
    const pState = states[pIdx];
    const isActive = pIdx === activeIdx;
    
    return el("div", {
      className: "farkle-player-card" + (isActive ? " active" : ""),
      style: `padding: 16px 20px; margin-bottom: 10px; border-radius: 14px; border: 2px solid ${isActive ? "var(--sunset-soft)" : "rgba(255,255,255,0.06)"}; background: ${isActive ? "rgba(255,145,100,0.04)" : "rgba(255,255,255,0.01)"}; display: flex; align-items: center; justify-content: space-between;`
    }, [
      el("div", {}, [
        el("div", { style: "display: flex; align-items: center; gap: 8px;" }, [
          el("h2", { text: name, style: "margin: 0; font-size:1.4rem;" }),
          pState.onBoard 
            ? el("span", { className: "badge", style: "background: rgba(0,250,150,0.1); color: #00ffaa; font-size: 0.75rem; border: 1px solid rgba(0,250,150,0.3); padding: 2px 8px;", text: "ON BOARD" })
            : el("span", { className: "badge", style: "background: rgba(255,255,255,0.03); color: #888; font-size: 0.75rem; border: 1px dashed rgba(255,255,255,0.15); padding: 2px 8px;", text: "NOT ON BOARD" })
        ]),
        el("div", { className: "muted", style: "font-size: 0.85rem; margin-top: 6px;" }, [
          document.createTextNode(pState.history.length > 0 ? `History: ${pState.history.join(", ")}` : "No rounds logged yet")
        ])
      ]),
      el("div", { style: "text-align: right;" }, [
        el("div", { text: String(pState.total), style: "font-size: 2rem; font-weight: bold; color: var(--sunset-soft);" }),
        el("div", { className: "muted", style: "font-size: 0.75rem;" }, [document.createTextNode("points")])
      ])
    ]);
  });

  const rollerPanel = el("div", {
    className: "panel center",
    style: "background: #0b1a20; padding: 20px; border: 1.5px solid rgba(255,255,255,0.08); border-radius: 16px; width: 100%; align-self: flex-start;"
  });

  const diceGrid = el("div", { style: "display: flex; gap: 12px; justify-content: center; flex-wrap: wrap; margin: 20px 0;" });
  if (state.virtualDice && state.virtualDice.length > 0) {
    state.virtualDice.forEach(die => {
      const dFace = renderDiceFaceSVG(die.val, die.held || die.scored);
      const box = el("div", {
        className: "dice-box" + (die.held ? " held" : "") + (die.scored ? " scored" : "") + (state.virtualRolling && !die.held && !die.scored ? " rolling" : ""),
        style: `width: 58px; height: 58px; padding: 4px; border: 2.5px solid ${die.scored ? "#00ffaa" : (die.held ? "var(--sunset-soft)" : "rgba(255,255,255,0.1)")}; border-radius: 10px;`
      }, [dFace]);
      diceGrid.appendChild(box);
    });
  } else {
    diceGrid.appendChild(el("div", { className: "muted", text: "Ready to roll...", style: "font-size:1.1rem; padding: 20px;" }));
  }

  rollerPanel.appendChild(el("h3", { text: `${activePlayerName}'s Rolling Cup`, style: "margin:0; font-size:1.4rem; color:var(--sunset-soft);" }));
  rollerPanel.appendChild(el("p", { className: "muted", text: `Running Score: ${state.turnTempScore} • Unused Dice Remaining: ${state.turnRemainingDice}`, style: "font-size:1rem; margin-top:8px;" }));
  rollerPanel.appendChild(diceGrid);

  mount(
    diceTopbar(`Farkle Broadcast: ${roomCode}`, () => renderTVConnectScreen()),
    el("div", {
      className: "farkle-board-layout",
      style: "display: grid; grid-template-columns: 1fr 1fr; gap: 24px; max-width: 900px; margin: 40px auto; padding: 12px;"
    }, [
      el("div", {}, [
        el("h2", { text: "Current Standings", style: "font-size: 1.3rem; margin-top: 0; letter-spacing: 0.5px; color:#00ffaa;" }),
        ...playerBlocks
      ]),
      rollerPanel
    ])
  );
}

function triggerTVRollAnimation(diceValues) {
  if (!gState) return;
  gState.virtualRolling = true;
  
  if (gState.virtualDice.length === 0) {
    gState.virtualDice = Array(6).fill(null).map(() => ({ val: 1, held: false, scored: false }));
  }

  let clicks = 0;
  const limit = 8;
  const interval = setInterval(() => {
    gState.virtualDice.forEach(d => {
      if (!d.scored && !d.held) d.val = Math.floor(Math.random() * 6) + 1;
    });
    renderFarkleTV(gState);
    playClickTone(450 + Math.random() * 100, 0.03);
    clicks++;

    if (clicks >= limit) {
      clearInterval(interval);
      gState.virtualRolling = false;
      gState.virtualDice.forEach((d, idx) => {
        d.val = diceValues[idx];
      });
      playClickTone(700, 0.06);
      renderFarkleTV(gState);
    }
  }, 80);
}

// ── 4. Deck & Card Games TV Broadcast View ────────────────────────────────────
function renderCardsTV(state) {
  // Determine card text and title
  const title = gState.prompt ? "Cards Against Monkeys" : "Would You Rather";
  const cardText = gState.prompt ? gState.prompt.text : (gState.text || "Draw a card to start play!");

  mount(
    tvTopbar(`${title} Broadcast: Room ${roomCode}`, () => renderTVConnectScreen()),
    el("div", { className: "panel center", style: "max-width: 600px; margin: 60px auto; padding: 32px;" }, [
      el("div", {
        className: "play-card prompt",
        style: "font-size:2.2rem; min-height:220px; line-height:1.4; justify-content:center; text-align:center; padding:30px; margin-bottom:20px;"
      }, [el("span", { text: cardText })]),
      gState.prompt && gState.submissions ? el("p", {
        className: "muted anim-pulse",
        style: "font-size:1.15rem; font-weight:bold;",
        text: `Submissions: ${gState.submissions.length} / ${gState.players.length - 1} connected players ready`
      }) : null
    ])
  );
}
